### ISSUE TITLE
google/protobuf error

### ISSUE THREAD

**Issue by Ulf3000** [vladvrabie/material-recommender#2]
```
Traceback (most recent call last):
  File "C:\Program Files No Install\BLENDER\blender-2.90.0-9cbf43801ba2-windows64\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Ulf3000\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\material_recommender\__init__.py", line 23, in <module>
    from . operators.preferences.generator import PreferencesListGenerator
  File "C:\Users\Ulf3000\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\material_recommender\operators\preferences\generator.py", line 3, in <module>
    from material_recommender.gms import cnn
  File "C:\Users\Ulf3000\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\material_recommender\gms\cnn.py", line 11, in <module>
    from keras import backend as K
  File "C:\Program Files No Install\BLENDER\blender-2.90.0-9cbf43801ba2-windows64\2.90\python\lib\site-packages\keras\__init__.py", line 3, in <module>
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 959, in _find_and_load_unlocked
  File "C:\Program Files No Install\BLENDER\blender-2.90.0-9cbf43801ba2-windows64\2.90\python\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Program Files No Install\BLENDER\blender-2.90.0-9cbf43801ba2-windows64\2.90\python\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Program Files No Install\BLENDER\blender-2.90.0-9cbf43801ba2-windows64\2.90\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Program Files No Install\BLENDER\blender-2.90.0-9cbf43801ba2-windows64\2.90\python\lib\site-packages\tensorflow_core\__init__.py", line 42, in <module>
    from . _api.v2 import audio
  File "C:\Program Files No Install\BLENDER\blender-2.90.0-9cbf43801ba2-windows64\2.90\python\lib\site-packages\tensorflow_core\_api\v2\audio\__init__.py", line 10, in <module>
    from tensorflow.python.ops.gen_audio_ops import decode_wav
  File "C:\Program Files No Install\BLENDER\blender-2.90.0-9cbf43801ba2-windows64\2.90\python\lib\site-packages\tensorflow_core\python\ops\gen_audio_ops.py", line 9, in <module>
    from tensorflow.python.eager import context as _context
  File "C:\Program Files No Install\BLENDER\blender-2.90.0-9cbf43801ba2-windows64\2.90\python\lib\site-packages\tensorflow_core\python\eager\context.py", line 29, in <module>
    from tensorflow.core.protobuf import config_pb2
  File "C:\Program Files No Install\BLENDER\blender-2.90.0-9cbf43801ba2-windows64\2.90\python\lib\site-packages\tensorflow_core\core\protobuf\config_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Program Files No Install\BLENDER\blender-2.90.0-9cbf43801ba2-windows64\2.90\python\lib\site-packages\google\protobuf\__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 594, in spec_from_file_location
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\Temp\\tmppi3ls4m9\\setuptools-41.2.0-py2.py3-none-any.whl'


```

from the blender output when i try to enable the addon , environment is conda python 3.7. no idea , is it supposed to download something can i manually solve this ?

**Comment by Ulf3000** [comment]
ok this was resolved by installing tensorflow-gpu

./python -m pip install tensorflow-gpu
